#!/usr/bin/env python3
"""
generate_ascii_db.py

Reads a markdown file of distro ASCII art entries in the format:

    ## 1. adelie

```text
    ...art...
```

    ## 2. aeon

```text
    ...art...
```

and emits cpp/Linux/core/linux_ascii_database.cpp — a flat
std::map<std::string, DistroArt> literal matching
include/core/linux_ascii_database.h.

Usage:
    python3 generate_ascii_db.py
    (interactively asks for the .md input path and the .cpp output path)
"""

import re
import sys
from pathlib import Path

# ------------------------------------------------------------------
# Known alias table — the markdown source only has one name per
# entry, so aliases (variant IDs that should resolve to the same
# art) are supplied here, keyed by the distro name as it appears
# in the markdown heading. Anything not listed gets an empty
# alias list — still valid, just no extra fallback IDs.
# ------------------------------------------------------------------
KNOWN_ALIASES = {
    "arch":     ["archlinux", "arch-linux"],
    "debian":   [],
    "fedora":   ["fedora-workstation", "fedora-server"],
    "manjaro":  ["manjaro-linux"],
    "pop":      ["pop_os", "popos", "pop!_os"],
    "ubuntu":   ["ubuntu-desktop", "ubuntu-server"],
    "linux":    ["generic", "unknown"],
    # add more as needed — anything absent here just gets [] below
}

HEADING_BLOCK_RE = re.compile(
    r"##\s*\d+\.\s*(\S+)\s*\n+```text\s*\n(.*?)```",
    re.DOTALL,
)


def parse_markdown(md_path: Path):
    """Returns a list of (key, art_text) tuples, in file order."""
    content = md_path.read_text(encoding="utf-8")
    entries = []

    for match in HEADING_BLOCK_RE.finditer(content):
        name = match.group(1).strip().lower()
        art = match.group(2)

        # Trim exactly one trailing newline before the closing ```,
        # keep internal formatting/color tags exactly as written.
        if art.endswith("\n"):
            art = art[:-1]

        entries.append((name, art))

    return entries


def pick_raw_delimiter(art: str) -> str:
    """
    R"ART(...)ART" is used by default. If an art string happens to
    contain the literal sequence )ART" (astronomically unlikely but
    checked anyway), fall back to a delimiter guaranteed not to
    collide, so the generated .cpp always compiles.
    """
    base = "ART"
    if f")ART\"" not in art:
        return base
    i = 0
    while f")ART{i}\"" in art:
        i += 1
    return f"ART{i}"


def format_entry(key: str, art: str, aliases):
    delim = pick_raw_delimiter(art)
    alias_str = ", ".join(f'"{a}"' for a in aliases)
    return (
        f'    {{ "{key}", {{\n'
        f'        R"{delim}(\n{art}\n)' + f'{delim}",\n'
        f'        {{{alias_str}}}\n'
        f'    }}}},\n'
    )


def generate_cpp(entries, output_path: Path):
    # Ensure a "linux" fallback entry always exists — mandatory per
    # the database's design (getDistroArt() must be a total function).
    keys = {k for k, _ in entries}
    if "linux" not in keys:
        print("Warning: no 'linux' entry found in markdown — "
              "injecting a minimal placeholder fallback.")
        entries.append((
            "linux",
            "$7    .--.\n$7   |o_o |\n$7   |:_/ |\n"
            "$7  //   \\ \\\n$7 (|     | )\n$7/'\\_   _/`\\\n$7\\___)=(___/",
        ))

    # Alphabetical, matching the design doc's convention.
    entries.sort(key=lambda e: e[0])

    header = (
        '#include "core/linux_ascii_database.h"\n\n'
        "// Auto-generated by generate_ascii_db.py — do not hand-edit.\n"
        "// Regenerate from the source markdown instead.\n"
        "//\n"
        "// One flat table, alphabetical by key. Key = ID= from\n"
        "// /etc/os-release (lowercase, one word). $N tags are parsed\n"
        "// by the existing processColorCodes() pipeline in AsciiArt.cpp.\n"
        "static const std::map<std::string, DistroArt> kDistroArtDB = {\n\n"
    )

    body = ""
    for key, art in entries:
        aliases = KNOWN_ALIASES.get(key, [])
        body += format_entry(key, art, aliases) + "\n"

    footer = (
        "};\n\n"
        "const std::map<std::string, DistroArt>& getDistroArtDatabase() {\n"
        "    return kDistroArtDB;\n"
        "}\n\n"
        "const std::string& getDistroArt(const std::string& distroId) {\n"
        "    if (auto it = kDistroArtDB.find(distroId); it != kDistroArtDB.end()) {\n"
        "        return it->second.art;\n"
        "    }\n"
        "    for (const auto& [key, entry] : kDistroArtDB) {\n"
        "        for (const auto& alias : entry.aliases) {\n"
        "            if (alias == distroId) return entry.art;\n"
        "        }\n"
        "    }\n"
        "    return kDistroArtDB.at(\"linux\").art;\n"
        "}\n"
    )

    output_path.write_text(header + body + footer, encoding="utf-8")


def main():
    md_input = input("Path to the markdown art database file: ").strip().strip('"')
    md_path = Path(md_input).expanduser().resolve()

    if not md_path.is_file():
        print(f"Error: file not found: {md_path}")
        sys.exit(1)

    out_input = input(
        "Output path for linux_ascii_database.cpp "
        "(e.g. src/BinaryFetch/cpp/Linux/core/linux_ascii_database.cpp): "
    ).strip().strip('"')
    output_path = Path(out_input).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    entries = parse_markdown(md_path)
    if not entries:
        print("Error: no entries found — check the markdown heading/"
              "```text fence format matches what this script expects.")
        sys.exit(1)

    print(f"Parsed {len(entries)} entries from {md_path.name}")
    generate_cpp(entries, output_path)
    print(f"Wrote: {output_path}")


if __name__ == "__main__":
    main()